language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
sudo: false

install:
  - travis_retry composer update && composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml ./tests

before_install:
  - pip install --user codecov
after_success:
  - codecov

matrix:
  allow_failures:
    - php: hhvm
